from app.schemas.user import *
from app.schemas.token import *
from app.schemas.event import *
from app.schemas.eventType import *
from app.schemas.classroom import *
from app.schemas.subscription import *
from app.schemas.subscription_template import *
from app.schemas.paymentType import *
from app.schemas.payment import *
from app.schemas.slot import *
from app.schemas.student import *
from app.schemas.level import *
from app.schemas.teacher import *
from app.schemas.lesson_type import *
